name: Tests

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  rspec:
    name: rspec tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Ruby
        uses: ruby/setup-ruby@4dc28cf14d77b0afa6832d9765ac422dbf0dfedd # v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Run rspec tests
        run: |
          bundle exec rspec

      - name: Upload coverage results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          include-hidden-files: 'true'
          name: coverage-results
          path: coverage
          retention-days: 5

  coverage:
    needs: rspec
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: coverage-results
          path: coverage

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@7fd5fa551dd583dd437a11c640b2a1cf23d6cdaa
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 70
          resultPath: coverage/.last_run.json
